### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension. - 2.6.1.pre.beta.2

### ISSUE THREAD

**Issue by erikjenks** [instructure/pulsar-client-ruby#28]
Currently on an M1 mac arm64
Receiving an error when trying to `bundle install` as well as trying to install via `gem install pulsar-client -v '2.6.1.pre.beta.2'`

Does anyone happen to have any ideas on how to solve this? Any help would be appreciated.

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/pulsar-client-ruby-343b1b8d81a2/ext/bindings
/Users/erik.jenks/.rbenv/versions/2.7.5/bin/ruby -I /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0 -r ./siteconf20220211-27839-wn8al.rb extconf.rb
creating Makefile

current directory: /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/pulsar-client-ruby-343b1b8d81a2/ext/bindings
make "DESTDIR=" clean

current directory: /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/pulsar-client-ruby-343b1b8d81a2/ext/bindings
make "DESTDIR="
compiling bindings.cpp
In file included from bindings.cpp:1:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/Module.hpp:5:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/Module.ipp:4:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/Module_impl.ipp:1:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/define_method_and_auto_wrap.hpp:29:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/define_method_and_auto_wrap.ipp:4:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/wrap_function.hpp:10:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/Exception_Handler.hpp:5:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/Exception_Handler.ipp:1:
/Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/../Data_Type_defn.hpp:207:10: warning: 'auto_ptr<Rice::detail::Abstract_Caster>'
is deprecated [-Wdeprecated-declarations]
  static std_unique_ptr<detail::Abstract_Caster> caster_;
         ^
/Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/ruby.hpp:74:29: note: expanded from macro 'std_unique_ptr'
#define std_unique_ptr std::auto_ptr
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:1186:28: note: 'auto_ptr<Rice::detail::Abstract_Caster>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 auto_ptr
                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1063:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1052:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from bindings.cpp:1:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/../Module.hpp:5:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/Module.ipp:4:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/Module_impl.ipp:1:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/define_method_and_auto_wrap.hpp:29:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/define_method_and_auto_wrap.ipp:4:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/wrap_function.hpp:10:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/Exception_Handler.hpp:5:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/Exception_Handler.ipp:1:
In file included from /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/Data_Type_defn.hpp:258:
/Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/Data_Type.ipp:20:1: warning: 'auto_ptr<Rice::detail::Abstract_Caster>' is deprecated
[-Wdeprecated-declarations]
std_unique_ptr<Rice::detail::Abstract_Caster> Rice::Data_Type<T>::caster_;
^
/Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rice-2.2.0/ruby/lib/include/rice/detail/ruby.hpp:74:29: note: expanded from macro 'std_unique_ptr'
#define std_unique_ptr std::auto_ptr
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:1186:28: note: 'auto_ptr<Rice::detail::Abstract_Caster>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 auto_ptr
                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1063:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1052:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from bindings.cpp:3:
./message.hpp:8:10: fatal error: 'pulsar/Client.h' file not found
#include <pulsar/Client.h>
         ^~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.
make: *** [bindings.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/pulsar-client-ruby-343b1b8d81a2 for inspection.
Results logged to /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/extensions/arm64-darwin-21/2.7.0/pulsar-client-ruby-343b1b8d81a2/gem_make.out

  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `each'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `make'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tempfile.rb:291:in `open'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in build_extension'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in build_extensions'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/source/path/installer.rb:34:in `post_install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/source/path.rb:244:in `generate_bin'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/source/git.rb:194:in `install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:171:in `install_serially'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:97:in `call'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer.rb:259:in `install_in_parallel'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer.rb:209:in `install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer.rb:89:in `block in run'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/process_lock.rb:9:in `open'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/process_lock.rb:9:in `lock'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer.rb:71:in `run'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/installer.rb:23:in `install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/cli/install.rb:62:in `run'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/cli.rb:255:in `block in install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/settings.rb:131:in `temporary'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/cli.rb:254:in `install'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/cli.rb:31:in `dispatch'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/cli.rb:25:in `start'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/exe/bundle:48:in `block in <top (required)>'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/erik.jenks/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/exe/bundle:36:in `<top (required)>'
  /Users/erik.jenks/.rbenv/versions/2.7.5/bin/bundle:23:in `load'
  /Users/erik.jenks/.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'

An error occurred while installing pulsar-client (2.6.1.pre.beta.2), and Bundler cannot continue.
```

**Comment by erikjenks** [comment]
Turns out the issue is with the rice gem. Since it's pinned to 2.2.0 it doesn't support the new M1 architecture. The most recent version of rice seems to, but that's 2 major versions ahead of what this project uses. Any plans to upgrade?

**Comment by Seitk** [comment]
I think it tells that the c++ client is missing from your environment. To build the bindings, both shared and static libraries of c++ client are required
